name: GitHub Actions Demo
on: [push]
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.fossaApiKey}}
          run-tests: true
      - uses: actions/checkout@v2
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json'

